

import {
  Archive,
  BarChart2,
  Bot,
  Boxes,
  BriefcaseBusiness,
  CalendarCheck,
  ClipboardList,
  FileText,
  Folder,
  FolderKanban,
  GraduationCap,
  IndianRupee,
  Key,
  LayoutDashboard,
  Layers,
  Library,
  Megaphone,
  MessageSquare,
  Newspaper,
  Percent,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Palette,
  Target,
  Users,
  Wallet,
  BrainCircuit,
  Clock,
  Plug,
} from "lucide-react";

import LinkedInIcon from "@/components/icons/LinkedInIcon";



export const navMenu = [
  {
    label: "Marketing",
    path: "/marketing",
    moduleKey: "MARKETING",
    icon: Sparkles,
    subItems: [
      {
        label: "Performance Console",
        path: "/marketing",
        icon: LayoutDashboard,
      },
      {
        label: "Opportunity Tracking",
        path: "/marketing/lead-management",
        icon: Target,
      },
      { label: "Campaign Mission", path: "/marketing/campaigns", icon: Megaphone },
      // { label: "Automation", path: "/marketing/automation", icon: Zap },
      // {
      //   label: "Landing Pages & Forms",
      //   path: "/marketing/landing-pages-forms",
      //   icon: FileText,
      // },
      {
        label: "Revenue Intelligence",
        path: "/marketing/marketing-analytics",
        icon: BarChart2,
      },
    ],
  },
  {
    label: "Student Hub",
    accessKey: "Student CRM",
    moduleKey: "STUDENT_CRM",
    path: "/student-crm",
    homePath: "/student-crm/dashboard",
    icon: Users,
    subItems: [
      {
        label: "Dashboard",
        path: "/student-crm/dashboard",
        icon: LayoutDashboard,
      },
      {
        label: "Application Tracking System",
        path: "/student-crm/applications",
        icon: ClipboardList,
      },
    ],
  },
  {
    label: "Agent Hub",
    accessKey: "Agency CRM",
    moduleKey: "AGENCY_CRM",
    path: "/agency-crm/agency-management",
    icon: Folder,
    subItems: [
      {
        label: "Agency Management",
        path: "/agency-crm/agency-management",
        icon: Users,
        /** admin = staff partner ops; agent = portal; all = both */
        audience: "admin",
      },
      {
        label: "Students & Referrals",
        agentLabel: "My Referrals",
        path: "/agency-crm/agency-leads",
        icon: ClipboardList,
        audience: "all",
      },
      {
        label: "University Directory",
        agentLabel: "Universities",
        path: "/agency-crm/universities",
        icon: GraduationCap,
        audience: "all",
      },
      {
        label: "Communications",
        agentLabel: "Notifications",
        path: "/agency-crm/communications",
        icon: MessageSquare,
        audience: "all",
      },
      {
        label: "Co-branding Tools",
        agentLabel: "Referral & Branding",
        path: "/agency-crm/co-branding-tools",
        icon: Layers,
        audience: "all",
      },
      {
        label: "Commission Management",
        agentLabel: "My Commissions",
        path: "/agency-crm/commission-management",
        icon: Percent,
        audience: "all",
      },
    ],
  },
  {
    label: "Communication",
    path: "/communication",
    icon: MessageSquare,
    accessKey: "Student Hub",
    moduleKey: "STUDENT_CRM",
  },

  {
    label: "Human Resource",
    accessKey: "HR",
    moduleKey: "HR",
    path: "/hr",
    icon: ShieldCheck,
    subItems: [
      { label: "Employee Directory", path: "/hr/employee-directory", icon: Users, permission: ["VIEW_ALL_EMPLOYEES", "MANAGE_EMPLOYEES"] },
      { label: "My HR", path: "/hr/me", icon: Clock, permission: ["VIEW_HR"] },
      { label: "Recruitment", path: "/hr/recruitment-tracker", icon: Search, permission: ["MANAGE_EMPLOYEES"] },
      { label: "Attendance", path: "/hr/attendance", icon: Clock, permission: ["VIEW_ATTENDANCE", "MANAGE_ATTENDANCE"] },
      { label: "Leave", path: "/hr/leave-management", icon: CalendarCheck, permission: ["VIEW_LEAVE", "MANAGE_LEAVE"] },
      { label: "Performance", path: "/hr/performance-reviews", icon: Star, permission: ["VIEW_REPORTS", "MANAGE_EMPLOYEES"] },
      { label: "Payroll", path: "/hr/payroll", icon: IndianRupee, permission: ["MANAGE_PAYROLL", "VIEW_OWN_PAYSLIP"] },
    ],
  },
  {
    label: "Knowledge Hub",
    accessKey: "Resources",
    moduleKey: "RESOURCES",
    path: "/resources",
    icon: Library,
    subItems: [
      { label: "Knowledge Library", path: "/resources", icon: FileText, permission: ["VIEW_RESOURCES", "MANAGE_RESOURCES"] },
      { label: "Upload Knowledge", path: "/resources/manage", icon: Folder, permission: ["MANAGE_RESOURCES"] },
    ],
  },
  {
    label: "Training",
    path: "/training",
    moduleKey: "TRAINING",
    icon: GraduationCap,
    subItems: [
      { label: "My Training", path: "/training", icon: GraduationCap, permission: ["VIEW_TRAINING", "MANAGE_TRAINING"] },
      { label: "Manage Training", path: "/training/manage", icon: ClipboardList, permission: ["MANAGE_TRAINING"] },
    ],
  },
  {
    label: "Admin & Settings",
    path: "/admin-settings",
    moduleKey: "ADMIN",
    icon: SlidersHorizontal,
    subItems: [
      { label: "Users", path: "/admin-settings/users", icon: Users, permission: ["MANAGE_EMPLOYEES", "MANAGE_ADMINS"] },
      {
        label: "Roles & Permissions",
        path: "/admin-settings/roles-permissions",
        icon: Key,
        permission: ["VIEW_ADMIN", "MANAGE_ADMINS"],
      },
      {
        label: "Appearance",
        path: "/admin-settings/branding",
        icon: Palette,
        permission: ["VIEW_ADMIN", "MANAGE_SYSTEM", "MANAGE_ADMINS"],
      },
    ],
  },
  {
    label: "Allied Services",
    path: "/allied-services",
    installFeature: "alliedServices",
    icon: BriefcaseBusiness,
  },
  {
    label: "Operations",
    path: "/operations",
    icon: Settings2,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
  {
    label: "Finance",
    path: "/finance",
    icon: Wallet,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
  {
    label: "Inventory Management",
    displayLabel: "Inventory",
    path: "/inventory-management",
    icon: Boxes,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
  {
    label: "Project Management",
    displayLabel: "Projects",
    path: "/project-management",
    icon: FolderKanban,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
  {
    label: "Chatbot & Events",
    path: "/chatbot-events",
    icon: Bot,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
  {
    label: "Blogs & News",
    path: "/blogs-news",
    icon: Newspaper,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
  {
    label: "AI Insights",
    path: "/ai-insights",
    icon: BrainCircuit,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
  {
    label: "Connector",
    path: "/connector",
    icon: Plug,
    navTheme: "crimson",
    installFeature: "sampleModules",
    subItems: [
      {
        label: "LinkedIn Plugin",
        path: "/connector/linkedin-plugin",
        icon: LinkedInIcon,
      },
    ],
  },
  {
    label: "Archive",
    path: "/archive",
    icon: Archive,
    navTheme: "crimson",
    installFeature: "sampleModules",
  },
];
