

import {
  BarChart2,
  BarChart3,
  Bell,
  Briefcase,
  Calendar,
  CalendarCheck,
  CheckSquare,
  ClipboardList,
  Cpu,
  CreditCard,
  File,
  FileText,
  Folder,
  GraduationCap,BriefcaseBusiness,
  Globe,
  Image,
  IndianRupee,
  Key,
  LayoutDashboard,
  Layers,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Percent,
  Plane,
  RotateCcw,
  Search,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Target,
  TrendingDown,
  TrendingUp,
  Users,
  Wallet,
  Zap,
  Lightbulb,
  Clock,
  Library,
} from "lucide-react";



export const navMenu = [
  {
    label: "Marketing",
    path: "/marketing",
    icon: Sparkles,
    subItems: [
      {
        label: "Performance Console",
        path: "/marketing",
        icon: LayoutDashboard,
      },
      {
        label: "Opportunity Tracking",
        path: "/marketing/lead-management",
        icon: Target,
      },
      { label: "Campaign Mission", path: "/marketing/campaigns", icon: Megaphone },
      // { label: "Automation", path: "/marketing/automation", icon: Zap },
      // {
      //   label: "Landing Pages & Forms",
      //   path: "/marketing/landing-pages-forms",
      //   icon: FileText,
      // },
      {
        label: "Revenue Intelligence",
        path: "/marketing/marketing-analytics",
        icon: BarChart2,
      },
    ],
  },
  {
    label: "Student Hub",
    accessKey: "Student CRM",
    path: "/student-crm/student-management",
    icon: Users,
    subItems: [
      {
        label: "Student Information Hub",
        path: "/student-crm/student-management",
        icon: GraduationCap,
      },
      {
        label: "Application Tracking System",
        path: "/student-crm/applications",
        icon: ClipboardList,
      },
      {
        label: "Visa management",
        path: "/student-crm/visa-management",
        icon: Plane,
      },
    ],
  },
  {
    label: "Agent Hub",
    accessKey: "Agency CRM",
    path: "/agency-crm/dashboard",
    icon: Folder,
    subItems: [
      {
        label: "Dashboard",
        path: "/agency-crm/dashboard",
        icon: LayoutDashboard,
        audience: "all",
      },
      {
        label: "Agency Management",
        path: "/agency-crm/agency-management",
        icon: Users,
        /** admin = staff partner ops; agent = portal; all = both */
        audience: "admin",
      },
      {
        label: "Students & Referrals",
        agentLabel: "My Referrals",
        path: "/agency-crm/agency-leads",
        icon: ClipboardList,
        audience: "all",
      },
      {
        label: "University Directory",
        agentLabel: "Universities",
        path: "/agency-crm/universities",
        icon: GraduationCap,
        audience: "all",
      },
      {
        label: "Onboarding",
        agentLabel: "My Profile & Onboarding",
        path: "/agency-crm/onboarding",
        icon: FileText,
        audience: "all",
      },
      {
        label: "Communications",
        agentLabel: "Notifications",
        path: "/agency-crm/communications",
        icon: MessageSquare,
        audience: "all",
      },
      {
        label: "Co-branding Tools",
        agentLabel: "Referral & Branding",
        path: "/agency-crm/co-branding-tools",
        icon: Layers,
        audience: "all",
      },
      {
        label: "Commission Management",
        agentLabel: "My Commissions",
        path: "/agency-crm/commission-management",
        icon: Percent,
        audience: "all",
      },
    ],
  },

  {
    label: "Human Resource",
    accessKey: "HR",
    path: "/hr",
    icon: ShieldCheck,
    subItems: [
      { label: "Employee Directory", path: "/hr/employee-directory", icon: Users, permission: ["VIEW_ALL_EMPLOYEES", "MANAGE_EMPLOYEES"] },
      { label: "My HR", path: "/hr/me", icon: Clock, permission: ["VIEW_HR"] },
      { label: "Recruitment", path: "/hr/recruitment-tracker", icon: Search, permission: ["MANAGE_EMPLOYEES"] },
      { label: "Attendance", path: "/hr/attendance", icon: Clock, permission: ["VIEW_ATTENDANCE", "MANAGE_ATTENDANCE"] },
      { label: "Leave", path: "/hr/leave-management", icon: CalendarCheck, permission: ["VIEW_LEAVE", "MANAGE_LEAVE"] },
      { label: "Performance", path: "/hr/performance-reviews", icon: Star, permission: ["VIEW_REPORTS", "MANAGE_EMPLOYEES"] },
      { label: "Payroll", path: "/hr/payroll", icon: IndianRupee, permission: ["MANAGE_PAYROLL", "VIEW_OWN_PAYSLIP"] },
    ],
  },
  {
    label: "Knowledge Hub",
    accessKey: "Resources",
    path: "/resources",
    icon: Library,
    subItems: [
      { label: "Knowledge Library", path: "/resources", icon: FileText, permission: ["VIEW_RESOURCES", "MANAGE_RESOURCES"] },
      { label: "Upload Knowledge", path: "/resources/manage", icon: Folder, permission: ["MANAGE_RESOURCES"] },
    ],
  },
  {
    label: "Admin & Settings",
    path: "/admin-settings",
    icon: SlidersHorizontal,
    subItems: [
      { label: "Users", path: "/admin-settings/users", icon: Users, permission: ["MANAGE_EMPLOYEES", "MANAGE_ADMINS"] },
      {
        label: "Roles & Permissions",
        path: "/admin-settings/roles-permissions",
        icon: Key,
        permission: ["VIEW_ADMIN", "MANAGE_ADMINS"],
      },
    ],
  },
  {
    label: "Allied Services",
    path: "/allied-services",
    icon: BriefcaseBusiness,
  },
   
];
