type ReceiptPayment = {
  id: number;
  receiptNumber: string | null;
  amountPaise: number;
  currency: string;
  paidAt: Date | null;
  razorpayPaymentId: string | null;
  razorpayOrderId: string | null;
  fee: { label: string | null; feeType: string | null } | null;
  application: {
    applicationCode: string;
    university: string;
    course: string;
    country: string;
    student: { fullName: string; email: string } | null;
  };
  studentUser: { fullName: string; email: string };
};

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const formatInr = (paise: number) =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(paise / 100);

const formatDate = (value: Date | null) => {
  if (!value) return '—';
  return value.toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

export const buildPaymentReceiptHtml = (payment: ReceiptPayment) => {
  const studentName =
    payment.application.student?.fullName || payment.studentUser.fullName || 'Student';
  const studentEmail = payment.application.student?.email || payment.studentUser.email || '';
  const receiptNo = payment.receiptNumber || `RCPT-${payment.id}`;
  const feeLabel = payment.fee?.label || 'Application fee';

  const rows = [
    ['Receipt number', receiptNo],
    ['Payment date', formatDate(payment.paidAt)],
    ['Student', studentName],
    ['Email', studentEmail],
    ['Application', payment.application.applicationCode],
    ['University', payment.application.university],
    ['Course', payment.application.course],
    ['Country', payment.application.country],
    ['Fee', feeLabel],
    ['Amount', formatInr(payment.amountPaise)],
    ['Payment method', 'Razorpay (Online)'],
    ['Transaction ID', payment.razorpayPaymentId || '—'],
    ['Order ID', payment.razorpayOrderId || '—'],
    ['Status', 'PAID'],
  ];

  const tableRows = rows
    .map(
      ([label, value]) => `
        <tr>
          <td style="padding:10px 0;color:#737373;font-size:13px;width:38%;vertical-align:top;">${escapeHtml(label)}</td>
          <td style="padding:10px 0;color:#171717;font-size:13px;font-weight:500;vertical-align:top;">${escapeHtml(value)}</td>
        </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Payment Receipt ${escapeHtml(receiptNo)}</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#171717;background:#fff;">
  <div style="max-width:640px;margin:0 auto;padding:40px 32px;">
    <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:24px;border-bottom:1px solid #e5e5e5;padding-bottom:24px;margin-bottom:28px;">
      <div>
        <p style="margin:0;font-size:22px;font-weight:700;letter-spacing:-0.02em;">ApplyUniNow</p>
        <p style="margin:6px 0 0;font-size:12px;color:#737373;">Student application payment receipt</p>
      </div>
      <div style="text-align:right;">
        <p style="margin:0;font-size:11px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;color:#a3a3a3;">Receipt</p>
        <p style="margin:4px 0 0;font-size:14px;font-weight:600;">${escapeHtml(receiptNo)}</p>
      </div>
    </div>

    <p style="margin:0 0 20px;font-size:15px;line-height:1.6;color:#404040;">
      This confirms payment received for the fee listed below. Keep this receipt for your records.
    </p>

    <table style="width:100%;border-collapse:collapse;margin-bottom:32px;">
      <tbody>${tableRows}</tbody>
    </table>

    <div style="border-top:1px solid #e5e5e5;padding-top:20px;">
      <p style="margin:0;font-size:11px;color:#a3a3a3;line-height:1.5;">
        Generated by ApplyUniNow · This is a computer-generated receipt and does not require a signature.
      </p>
    </div>
  </div>
</body>
</html>`;
};
