SET search_path TO "onecrm", public;

ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NOT_CONTACTED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CALLBACK';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'FOLLOW_UP';

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "notContactedAt" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "callbackAt" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "followUpAt" TIMESTAMP(3);
