ALTER TABLE "University" ADD COLUMN IF NOT EXISTS "pocName" TEXT;
ALTER TABLE "University" ADD COLUMN IF NOT EXISTS "pocEmail" TEXT;
ALTER TABLE "University" ADD COLUMN IF NOT EXISTS "pocPhone" TEXT;
